// dart format width=80
// GENERATED BY drift_dev, DO NOT MODIFY.
// ignore_for_file: type=lint,unused_import
//
import 'package:drift/drift.dart';

class Players extends Table with TableInfo {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  Players(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> createdAt = GeneratedColumn<String>(
    'created_at',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> updatedAt = GeneratedColumn<String>(
    'updated_at',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> version = GeneratedColumn<int>(
    'version',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL CHECK (version >= 0)',
  );
  late final GeneratedColumn<String> deletedAt = GeneratedColumn<String>(
    'deleted_at',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<String> id = GeneratedColumn<String>(
    'id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> displayName = GeneratedColumn<String>(
    'display_name',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL CHECK (trim(display_name) <> \'\')',
  );
  @override
  List<GeneratedColumn> get $columns => [
    createdAt,
    updatedAt,
    version,
    deletedAt,
    id,
    displayName,
  ];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'players';
  @override
  Set<GeneratedColumn> get $primaryKey => {id};
  @override
  Never map(Map<String, dynamic> data, {String? tablePrefix}) {
    throw UnsupportedError('TableInfo.map in schema verification code');
  }

  @override
  Players createAlias(String alias) {
    return Players(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const [
    'PRIMARY KEY(id)',
    'CHECK(updated_at >= created_at)',
    'CHECK(deleted_at IS NULL OR deleted_at >= updated_at)',
  ];
  @override
  bool get dontWriteConstraints => true;
}

class Events extends Table with TableInfo {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  Events(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> createdAt = GeneratedColumn<String>(
    'created_at',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> updatedAt = GeneratedColumn<String>(
    'updated_at',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> version = GeneratedColumn<int>(
    'version',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL CHECK (version >= 0)',
  );
  late final GeneratedColumn<String> deletedAt = GeneratedColumn<String>(
    'deleted_at',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<String> id = GeneratedColumn<String>(
    'id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> name = GeneratedColumn<String>(
    'name',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL CHECK (trim(name) <> \'\')',
  );
  late final GeneratedColumn<String> scheduledAt = GeneratedColumn<String>(
    'scheduled_at',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> eventType = GeneratedColumn<String>(
    'event_type',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints:
        'NOT NULL CHECK (event_type IN (\'casual\', \'formal\'))',
  );
  late final GeneratedColumn<String> status = GeneratedColumn<String>(
    'status',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL CHECK (status IN (\'upcoming\', \'registration\', \'inProgress\', \'completed\', \'archived\'))',
  );
  late final GeneratedColumn<int> entryFeeMinorUnits = GeneratedColumn<int>(
    'entry_fee_minor_units',
    aliasedName,
    true,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<String> entryFeeCurrency = GeneratedColumn<String>(
    'entry_fee_currency',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<String> courtLabel = GeneratedColumn<String>(
    'court_label',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL CHECK (trim(court_label) <> \'\')',
  );
  @override
  List<GeneratedColumn> get $columns => [
    createdAt,
    updatedAt,
    version,
    deletedAt,
    id,
    name,
    scheduledAt,
    eventType,
    status,
    entryFeeMinorUnits,
    entryFeeCurrency,
    courtLabel,
  ];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'events';
  @override
  Set<GeneratedColumn> get $primaryKey => {id};
  @override
  Never map(Map<String, dynamic> data, {String? tablePrefix}) {
    throw UnsupportedError('TableInfo.map in schema verification code');
  }

  @override
  Events createAlias(String alias) {
    return Events(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const [
    'PRIMARY KEY(id)',
    'CHECK((entry_fee_minor_units IS NULL AND entry_fee_currency IS NULL)OR(entry_fee_minor_units >= 0 AND entry_fee_currency GLOB \'[A-Z][A-Z][A-Z]\'))',
    'CHECK(updated_at >= created_at)',
    'CHECK(deleted_at IS NULL OR deleted_at >= updated_at)',
  ];
  @override
  bool get dontWriteConstraints => true;
}

class EventDivisions extends Table with TableInfo {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  EventDivisions(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> createdAt = GeneratedColumn<String>(
    'created_at',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> updatedAt = GeneratedColumn<String>(
    'updated_at',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> version = GeneratedColumn<int>(
    'version',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL CHECK (version >= 0)',
  );
  late final GeneratedColumn<String> deletedAt = GeneratedColumn<String>(
    'deleted_at',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<String> id = GeneratedColumn<String>(
    'id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> eventId = GeneratedColumn<String>(
    'event_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL REFERENCES events(id)ON DELETE RESTRICT',
  );
  late final GeneratedColumn<String> name = GeneratedColumn<String>(
    'name',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL CHECK (trim(name) <> \'\')',
  );
  late final GeneratedColumn<String> tournamentFormat = GeneratedColumn<String>(
    'tournament_format',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL CHECK (tournament_format IN (\'singleElimination\', \'doubleElimination\', \'singleRoundRobin\', \'doubleRoundRobin\'))',
  );
  @override
  List<GeneratedColumn> get $columns => [
    createdAt,
    updatedAt,
    version,
    deletedAt,
    id,
    eventId,
    name,
    tournamentFormat,
  ];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'event_divisions';
  @override
  Set<GeneratedColumn> get $primaryKey => {id};
  @override
  Never map(Map<String, dynamic> data, {String? tablePrefix}) {
    throw UnsupportedError('TableInfo.map in schema verification code');
  }

  @override
  EventDivisions createAlias(String alias) {
    return EventDivisions(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const [
    'PRIMARY KEY(id)',
    'CHECK(updated_at >= created_at)',
    'CHECK(deleted_at IS NULL OR deleted_at >= updated_at)',
  ];
  @override
  bool get dontWriteConstraints => true;
}

class EventParticipants extends Table with TableInfo {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  EventParticipants(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> createdAt = GeneratedColumn<String>(
    'created_at',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> updatedAt = GeneratedColumn<String>(
    'updated_at',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> version = GeneratedColumn<int>(
    'version',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL CHECK (version >= 0)',
  );
  late final GeneratedColumn<String> deletedAt = GeneratedColumn<String>(
    'deleted_at',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<String> id = GeneratedColumn<String>(
    'id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> eventId = GeneratedColumn<String>(
    'event_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL REFERENCES events(id)ON DELETE RESTRICT',
  );
  late final GeneratedColumn<String> playerId = GeneratedColumn<String>(
    'player_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL REFERENCES players(id)ON DELETE RESTRICT',
  );
  late final GeneratedColumn<String> checkInStatus = GeneratedColumn<String>(
    'check_in_status',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints:
        'NOT NULL CHECK (check_in_status IN (\'notPresent\', \'checkedIn\'))',
  );
  @override
  List<GeneratedColumn> get $columns => [
    createdAt,
    updatedAt,
    version,
    deletedAt,
    id,
    eventId,
    playerId,
    checkInStatus,
  ];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'event_participants';
  @override
  Set<GeneratedColumn> get $primaryKey => {id};
  @override
  Never map(Map<String, dynamic> data, {String? tablePrefix}) {
    throw UnsupportedError('TableInfo.map in schema verification code');
  }

  @override
  EventParticipants createAlias(String alias) {
    return EventParticipants(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const [
    'PRIMARY KEY(id)',
    'CHECK(updated_at >= created_at)',
    'CHECK(deleted_at IS NULL OR deleted_at >= updated_at)',
  ];
  @override
  bool get dontWriteConstraints => true;
}

class DivisionParticipants extends Table with TableInfo {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  DivisionParticipants(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> createdAt = GeneratedColumn<String>(
    'created_at',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> updatedAt = GeneratedColumn<String>(
    'updated_at',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> version = GeneratedColumn<int>(
    'version',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL CHECK (version >= 0)',
  );
  late final GeneratedColumn<String> deletedAt = GeneratedColumn<String>(
    'deleted_at',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<String> id = GeneratedColumn<String>(
    'id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> divisionId = GeneratedColumn<String>(
    'division_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints:
        'NOT NULL REFERENCES event_divisions(id)ON DELETE RESTRICT',
  );
  late final GeneratedColumn<String> eventParticipantId =
      GeneratedColumn<String>(
        'event_participant_id',
        aliasedName,
        false,
        type: DriftSqlType.string,
        requiredDuringInsert: true,
        $customConstraints:
            'NOT NULL REFERENCES event_participants(id)ON DELETE RESTRICT',
      );
  @override
  List<GeneratedColumn> get $columns => [
    createdAt,
    updatedAt,
    version,
    deletedAt,
    id,
    divisionId,
    eventParticipantId,
  ];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'division_participants';
  @override
  Set<GeneratedColumn> get $primaryKey => {id};
  @override
  Never map(Map<String, dynamic> data, {String? tablePrefix}) {
    throw UnsupportedError('TableInfo.map in schema verification code');
  }

  @override
  DivisionParticipants createAlias(String alias) {
    return DivisionParticipants(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const [
    'PRIMARY KEY(id)',
    'CHECK(updated_at >= created_at)',
    'CHECK(deleted_at IS NULL OR deleted_at >= updated_at)',
  ];
  @override
  bool get dontWriteConstraints => true;
}

class ParticipantPayments extends Table with TableInfo {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  ParticipantPayments(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> createdAt = GeneratedColumn<String>(
    'created_at',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> updatedAt = GeneratedColumn<String>(
    'updated_at',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> version = GeneratedColumn<int>(
    'version',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL CHECK (version >= 0)',
  );
  late final GeneratedColumn<String> deletedAt = GeneratedColumn<String>(
    'deleted_at',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<String> id = GeneratedColumn<String>(
    'id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> eventParticipantId =
      GeneratedColumn<String>(
        'event_participant_id',
        aliasedName,
        false,
        type: DriftSqlType.string,
        requiredDuringInsert: true,
        $customConstraints:
            'NOT NULL REFERENCES event_participants(id)ON DELETE RESTRICT',
      );
  late final GeneratedColumn<String> divisionId = GeneratedColumn<String>(
    'division_id',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NULL REFERENCES event_divisions(id)ON DELETE RESTRICT',
  );
  late final GeneratedColumn<String> status = GeneratedColumn<String>(
    'status',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL CHECK (status IN (\'unpaid\', \'paid\'))',
  );
  @override
  List<GeneratedColumn> get $columns => [
    createdAt,
    updatedAt,
    version,
    deletedAt,
    id,
    eventParticipantId,
    divisionId,
    status,
  ];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'participant_payments';
  @override
  Set<GeneratedColumn> get $primaryKey => {id};
  @override
  Never map(Map<String, dynamic> data, {String? tablePrefix}) {
    throw UnsupportedError('TableInfo.map in schema verification code');
  }

  @override
  ParticipantPayments createAlias(String alias) {
    return ParticipantPayments(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const [
    'PRIMARY KEY(id)',
    'CHECK(updated_at >= created_at)',
    'CHECK(deleted_at IS NULL OR deleted_at >= updated_at)',
  ];
  @override
  bool get dontWriteConstraints => true;
}

class Teams extends Table with TableInfo {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  Teams(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> createdAt = GeneratedColumn<String>(
    'created_at',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> updatedAt = GeneratedColumn<String>(
    'updated_at',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> version = GeneratedColumn<int>(
    'version',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL CHECK (version >= 0)',
  );
  late final GeneratedColumn<String> deletedAt = GeneratedColumn<String>(
    'deleted_at',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<String> id = GeneratedColumn<String>(
    'id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> divisionId = GeneratedColumn<String>(
    'division_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints:
        'NOT NULL REFERENCES event_divisions(id)ON DELETE RESTRICT',
  );
  late final GeneratedColumn<String> formationMethod = GeneratedColumn<String>(
    'formation_method',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL CHECK (formation_method IN (\'manual\', \'random\', \'balanced\'))',
  );
  late final GeneratedColumn<String> displayLabel = GeneratedColumn<String>(
    'display_label',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  @override
  List<GeneratedColumn> get $columns => [
    createdAt,
    updatedAt,
    version,
    deletedAt,
    id,
    divisionId,
    formationMethod,
    displayLabel,
  ];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'teams';
  @override
  Set<GeneratedColumn> get $primaryKey => {id};
  @override
  Never map(Map<String, dynamic> data, {String? tablePrefix}) {
    throw UnsupportedError('TableInfo.map in schema verification code');
  }

  @override
  Teams createAlias(String alias) {
    return Teams(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const [
    'PRIMARY KEY(id)',
    'CHECK(display_label IS NULL OR trim(display_label) <> \'\')',
    'CHECK(updated_at >= created_at)',
    'CHECK(deleted_at IS NULL OR deleted_at >= updated_at)',
  ];
  @override
  bool get dontWriteConstraints => true;
}

class TeamMembers extends Table with TableInfo {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  TeamMembers(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> createdAt = GeneratedColumn<String>(
    'created_at',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> updatedAt = GeneratedColumn<String>(
    'updated_at',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> version = GeneratedColumn<int>(
    'version',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL CHECK (version >= 0)',
  );
  late final GeneratedColumn<String> deletedAt = GeneratedColumn<String>(
    'deleted_at',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<String> teamId = GeneratedColumn<String>(
    'team_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL REFERENCES teams(id)ON DELETE RESTRICT',
  );
  late final GeneratedColumn<String> playerId = GeneratedColumn<String>(
    'player_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL REFERENCES players(id)ON DELETE RESTRICT',
  );
  @override
  List<GeneratedColumn> get $columns => [
    createdAt,
    updatedAt,
    version,
    deletedAt,
    teamId,
    playerId,
  ];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'team_members';
  @override
  Set<GeneratedColumn> get $primaryKey => {teamId, playerId};
  @override
  Never map(Map<String, dynamic> data, {String? tablePrefix}) {
    throw UnsupportedError('TableInfo.map in schema verification code');
  }

  @override
  TeamMembers createAlias(String alias) {
    return TeamMembers(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const [
    'PRIMARY KEY(team_id, player_id)',
    'CHECK(updated_at >= created_at)',
    'CHECK(deleted_at IS NULL OR deleted_at >= updated_at)',
  ];
  @override
  bool get dontWriteConstraints => true;
}

class Matches extends Table with TableInfo {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  Matches(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> createdAt = GeneratedColumn<String>(
    'created_at',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> updatedAt = GeneratedColumn<String>(
    'updated_at',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> version = GeneratedColumn<int>(
    'version',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL CHECK (version >= 0)',
  );
  late final GeneratedColumn<String> deletedAt = GeneratedColumn<String>(
    'deleted_at',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<String> id = GeneratedColumn<String>(
    'id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> divisionId = GeneratedColumn<String>(
    'division_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints:
        'NOT NULL REFERENCES event_divisions(id)ON DELETE RESTRICT',
  );
  late final GeneratedColumn<String> sideOneTeamId = GeneratedColumn<String>(
    'side_one_team_id',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NULL REFERENCES teams(id)ON DELETE RESTRICT',
  );
  late final GeneratedColumn<String> sideTwoTeamId = GeneratedColumn<String>(
    'side_two_team_id',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NULL REFERENCES teams(id)ON DELETE RESTRICT',
  );
  late final GeneratedColumn<String> status = GeneratedColumn<String>(
    'status',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL CHECK (status IN (\'scheduled\', \'queued\', \'inProgress\', \'completed\'))',
  );
  late final GeneratedColumn<int> sideOneScore = GeneratedColumn<int>(
    'side_one_score',
    aliasedName,
    true,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<int> sideTwoScore = GeneratedColumn<int>(
    'side_two_score',
    aliasedName,
    true,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<String> winnerTeamId = GeneratedColumn<String>(
    'winner_team_id',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NULL REFERENCES teams(id)ON DELETE RESTRICT',
  );
  late final GeneratedColumn<int> roundNumber = GeneratedColumn<int>(
    'round_number',
    aliasedName,
    true,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<int> sequenceNumber = GeneratedColumn<int>(
    'sequence_number',
    aliasedName,
    true,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  @override
  List<GeneratedColumn> get $columns => [
    createdAt,
    updatedAt,
    version,
    deletedAt,
    id,
    divisionId,
    sideOneTeamId,
    sideTwoTeamId,
    status,
    sideOneScore,
    sideTwoScore,
    winnerTeamId,
    roundNumber,
    sequenceNumber,
  ];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'matches';
  @override
  Set<GeneratedColumn> get $primaryKey => {id};
  @override
  Never map(Map<String, dynamic> data, {String? tablePrefix}) {
    throw UnsupportedError('TableInfo.map in schema verification code');
  }

  @override
  Matches createAlias(String alias) {
    return Matches(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const [
    'PRIMARY KEY(id)',
    'CHECK(side_one_team_id IS NULL OR side_two_team_id IS NULL OR side_one_team_id <> side_two_team_id)',
    'CHECK(side_one_score IS NULL OR side_one_score >= 0)',
    'CHECK(side_two_score IS NULL OR side_two_score >= 0)',
    'CHECK(round_number IS NULL OR round_number > 0)',
    'CHECK(sequence_number IS NULL OR sequence_number > 0)',
    'CHECK((status = \'completed\' AND side_one_team_id IS NOT NULL AND side_two_team_id IS NOT NULL AND side_one_score IS NOT NULL AND side_two_score IS NOT NULL AND winner_team_id IS NOT NULL AND winner_team_id IN (side_one_team_id, side_two_team_id))OR(status <> \'completed\' AND winner_team_id IS NULL))',
    'CHECK(updated_at >= created_at)',
    'CHECK(deleted_at IS NULL OR deleted_at >= updated_at)',
  ];
  @override
  bool get dontWriteConstraints => true;
}

class MatchDependencies extends Table with TableInfo {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  MatchDependencies(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> createdAt = GeneratedColumn<String>(
    'created_at',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> updatedAt = GeneratedColumn<String>(
    'updated_at',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> version = GeneratedColumn<int>(
    'version',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL CHECK (version >= 0)',
  );
  late final GeneratedColumn<String> deletedAt = GeneratedColumn<String>(
    'deleted_at',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<String> sourceMatchId = GeneratedColumn<String>(
    'source_match_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL REFERENCES matches(id)ON DELETE RESTRICT',
  );
  late final GeneratedColumn<String> sourceOutcome = GeneratedColumn<String>(
    'source_outcome',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints:
        'NOT NULL CHECK (source_outcome IN (\'winner\', \'loser\'))',
  );
  late final GeneratedColumn<String> destinationMatchId =
      GeneratedColumn<String>(
        'destination_match_id',
        aliasedName,
        false,
        type: DriftSqlType.string,
        requiredDuringInsert: true,
        $customConstraints: 'NOT NULL REFERENCES matches(id)ON DELETE RESTRICT',
      );
  late final GeneratedColumn<String> destinationSlot = GeneratedColumn<String>(
    'destination_slot',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints:
        'NOT NULL CHECK (destination_slot IN (\'sideOne\', \'sideTwo\'))',
  );
  @override
  List<GeneratedColumn> get $columns => [
    createdAt,
    updatedAt,
    version,
    deletedAt,
    sourceMatchId,
    sourceOutcome,
    destinationMatchId,
    destinationSlot,
  ];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'match_dependencies';
  @override
  Set<GeneratedColumn> get $primaryKey => {
    sourceMatchId,
    sourceOutcome,
    destinationMatchId,
    destinationSlot,
  };
  @override
  Never map(Map<String, dynamic> data, {String? tablePrefix}) {
    throw UnsupportedError('TableInfo.map in schema verification code');
  }

  @override
  MatchDependencies createAlias(String alias) {
    return MatchDependencies(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const [
    'PRIMARY KEY(source_match_id, source_outcome, destination_match_id, destination_slot)',
    'CHECK(source_match_id <> destination_match_id)',
    'CHECK(updated_at >= created_at)',
    'CHECK(deleted_at IS NULL OR deleted_at >= updated_at)',
  ];
  @override
  bool get dontWriteConstraints => true;
}

class CourtQueueEntries extends Table with TableInfo {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  CourtQueueEntries(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> createdAt = GeneratedColumn<String>(
    'created_at',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> updatedAt = GeneratedColumn<String>(
    'updated_at',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> version = GeneratedColumn<int>(
    'version',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL CHECK (version >= 0)',
  );
  late final GeneratedColumn<String> deletedAt = GeneratedColumn<String>(
    'deleted_at',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<String> id = GeneratedColumn<String>(
    'id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> eventId = GeneratedColumn<String>(
    'event_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL REFERENCES events(id)ON DELETE RESTRICT',
  );
  late final GeneratedColumn<String> divisionId = GeneratedColumn<String>(
    'division_id',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NULL REFERENCES event_divisions(id)ON DELETE RESTRICT',
  );
  late final GeneratedColumn<String> matchId = GeneratedColumn<String>(
    'match_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL REFERENCES matches(id)ON DELETE RESTRICT',
  );
  late final GeneratedColumn<int> queuePosition = GeneratedColumn<int>(
    'queue_position',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL CHECK (queue_position >= 0)',
  );
  @override
  List<GeneratedColumn> get $columns => [
    createdAt,
    updatedAt,
    version,
    deletedAt,
    id,
    eventId,
    divisionId,
    matchId,
    queuePosition,
  ];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'court_queue_entries';
  @override
  Set<GeneratedColumn> get $primaryKey => {id};
  @override
  Never map(Map<String, dynamic> data, {String? tablePrefix}) {
    throw UnsupportedError('TableInfo.map in schema verification code');
  }

  @override
  CourtQueueEntries createAlias(String alias) {
    return CourtQueueEntries(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const [
    'PRIMARY KEY(id)',
    'CHECK(updated_at >= created_at)',
    'CHECK(deleted_at IS NULL OR deleted_at >= updated_at)',
  ];
  @override
  bool get dontWriteConstraints => true;
}

class DivisionPlacements extends Table with TableInfo {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  DivisionPlacements(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> createdAt = GeneratedColumn<String>(
    'created_at',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> updatedAt = GeneratedColumn<String>(
    'updated_at',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> version = GeneratedColumn<int>(
    'version',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL CHECK (version >= 0)',
  );
  late final GeneratedColumn<String> deletedAt = GeneratedColumn<String>(
    'deleted_at',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<String> id = GeneratedColumn<String>(
    'id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> divisionId = GeneratedColumn<String>(
    'division_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints:
        'NOT NULL REFERENCES event_divisions(id)ON DELETE RESTRICT',
  );
  late final GeneratedColumn<String> teamId = GeneratedColumn<String>(
    'team_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL REFERENCES teams(id)ON DELETE RESTRICT',
  );
  late final GeneratedColumn<int> position = GeneratedColumn<int>(
    'position',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL CHECK (position > 0)',
  );
  @override
  List<GeneratedColumn> get $columns => [
    createdAt,
    updatedAt,
    version,
    deletedAt,
    id,
    divisionId,
    teamId,
    position,
  ];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'division_placements';
  @override
  Set<GeneratedColumn> get $primaryKey => {id};
  @override
  Never map(Map<String, dynamic> data, {String? tablePrefix}) {
    throw UnsupportedError('TableInfo.map in schema verification code');
  }

  @override
  DivisionPlacements createAlias(String alias) {
    return DivisionPlacements(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const [
    'PRIMARY KEY(id)',
    'CHECK(updated_at >= created_at)',
    'CHECK(deleted_at IS NULL OR deleted_at >= updated_at)',
  ];
  @override
  bool get dontWriteConstraints => true;
}

class SyncOutboxOperations extends Table with TableInfo {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  SyncOutboxOperations(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> id = GeneratedColumn<String>(
    'id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> entityType = GeneratedColumn<String>(
    'entity_type',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL CHECK (entity_type = \'player\')',
  );
  late final GeneratedColumn<String> entityId = GeneratedColumn<String>(
    'entity_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL REFERENCES players(id)ON DELETE RESTRICT',
  );
  late final GeneratedColumn<String> operationKind = GeneratedColumn<String>(
    'operation_kind',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints:
        'NOT NULL CHECK (operation_kind IN (\'upsert\', \'tombstone\'))',
  );
  late final GeneratedColumn<int> baseVersion = GeneratedColumn<int>(
    'base_version',
    aliasedName,
    true,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<String> payloadJson = GeneratedColumn<String>(
    'payload_json',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL CHECK (json_valid(payload_json) AND json_type(payload_json) = \'object\')',
  );
  late final GeneratedColumn<String> createdAt = GeneratedColumn<String>(
    'created_at',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> attemptCount = GeneratedColumn<int>(
    'attempt_count',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL DEFAULT 0',
    defaultValue: const CustomExpression('0'),
  );
  late final GeneratedColumn<String> nextEligibleAt = GeneratedColumn<String>(
    'next_eligible_at',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> status = GeneratedColumn<String>(
    'status',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL CHECK (status IN (\'pending\', \'inFlight\', \'conflicted\', \'failed\'))',
  );
  late final GeneratedColumn<String> claimedAt = GeneratedColumn<String>(
    'claimed_at',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<String> failureCode = GeneratedColumn<String>(
    'failure_code',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<String> failureMessage = GeneratedColumn<String>(
    'failure_message',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  @override
  List<GeneratedColumn> get $columns => [
    id,
    entityType,
    entityId,
    operationKind,
    baseVersion,
    payloadJson,
    createdAt,
    attemptCount,
    nextEligibleAt,
    status,
    claimedAt,
    failureCode,
    failureMessage,
  ];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'sync_outbox_operations';
  @override
  Set<GeneratedColumn> get $primaryKey => {id};
  @override
  Never map(Map<String, dynamic> data, {String? tablePrefix}) {
    throw UnsupportedError('TableInfo.map in schema verification code');
  }

  @override
  SyncOutboxOperations createAlias(String alias) {
    return SyncOutboxOperations(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const [
    'PRIMARY KEY(id)',
    'CHECK(base_version IS NULL OR base_version >= 0)',
    'CHECK(attempt_count >= 0)',
    'CHECK((status = \'inFlight\' AND claimed_at IS NOT NULL)OR(status <> \'inFlight\' AND claimed_at IS NULL))',
    'CHECK(failure_message IS NULL OR length(failure_message) <= 240)',
  ];
  @override
  bool get dontWriteConstraints => true;
}

class SyncPullCheckpoints extends Table with TableInfo {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  SyncPullCheckpoints(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> entityType = GeneratedColumn<String>(
    'entity_type',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL CHECK (entity_type = \'player\')',
  );
  late final GeneratedColumn<String> cursorUpdatedAt = GeneratedColumn<String>(
    'cursor_updated_at',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> cursorEntityId = GeneratedColumn<String>(
    'cursor_entity_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL REFERENCES players(id)ON DELETE RESTRICT',
  );
  late final GeneratedColumn<String> updatedAt = GeneratedColumn<String>(
    'updated_at',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  @override
  List<GeneratedColumn> get $columns => [
    entityType,
    cursorUpdatedAt,
    cursorEntityId,
    updatedAt,
  ];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'sync_pull_checkpoints';
  @override
  Set<GeneratedColumn> get $primaryKey => {entityType};
  @override
  Never map(Map<String, dynamic> data, {String? tablePrefix}) {
    throw UnsupportedError('TableInfo.map in schema verification code');
  }

  @override
  SyncPullCheckpoints createAlias(String alias) {
    return SyncPullCheckpoints(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const ['PRIMARY KEY(entity_type)'];
  @override
  bool get dontWriteConstraints => true;
}

class SyncConflicts extends Table with TableInfo {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  SyncConflicts(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> id = GeneratedColumn<String>(
    'id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> operationId = GeneratedColumn<String>(
    'operation_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL UNIQUE REFERENCES sync_outbox_operations(id)ON DELETE RESTRICT',
  );
  late final GeneratedColumn<String> entityType = GeneratedColumn<String>(
    'entity_type',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL CHECK (entity_type = \'player\')',
  );
  late final GeneratedColumn<String> entityId = GeneratedColumn<String>(
    'entity_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL REFERENCES players(id)ON DELETE RESTRICT',
  );
  late final GeneratedColumn<int> expectedVersion = GeneratedColumn<int>(
    'expected_version',
    aliasedName,
    true,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<String> localPayloadJson = GeneratedColumn<String>(
    'local_payload_json',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL CHECK (json_valid(local_payload_json) AND json_type(local_payload_json) = \'object\')',
  );
  late final GeneratedColumn<String> remotePayloadJson =
      GeneratedColumn<String>(
        'remote_payload_json',
        aliasedName,
        true,
        type: DriftSqlType.string,
        requiredDuringInsert: false,
        $customConstraints: 'NULL',
      );
  late final GeneratedColumn<int> remoteVersion = GeneratedColumn<int>(
    'remote_version',
    aliasedName,
    true,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<String> detectedAt = GeneratedColumn<String>(
    'detected_at',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> status = GeneratedColumn<String>(
    'status',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints:
        'NOT NULL CHECK (status IN (\'unresolved\', \'resolved\'))',
  );
  @override
  List<GeneratedColumn> get $columns => [
    id,
    operationId,
    entityType,
    entityId,
    expectedVersion,
    localPayloadJson,
    remotePayloadJson,
    remoteVersion,
    detectedAt,
    status,
  ];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'sync_conflicts';
  @override
  Set<GeneratedColumn> get $primaryKey => {id};
  @override
  Never map(Map<String, dynamic> data, {String? tablePrefix}) {
    throw UnsupportedError('TableInfo.map in schema verification code');
  }

  @override
  SyncConflicts createAlias(String alias) {
    return SyncConflicts(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const [
    'PRIMARY KEY(id)',
    'CHECK(expected_version IS NULL OR expected_version >= 0)',
    'CHECK(remote_version IS NULL OR remote_version >= 0)',
    'CHECK(remote_payload_json IS NULL OR(json_valid(remote_payload_json) AND json_type(remote_payload_json) = \'object\'))',
  ];
  @override
  bool get dontWriteConstraints => true;
}

class DatabaseAtV2 extends GeneratedDatabase {
  DatabaseAtV2(QueryExecutor e) : super(e);
  late final Players players = Players(this);
  late final Events events = Events(this);
  late final EventDivisions eventDivisions = EventDivisions(this);
  late final EventParticipants eventParticipants = EventParticipants(this);
  late final DivisionParticipants divisionParticipants = DivisionParticipants(
    this,
  );
  late final ParticipantPayments participantPayments = ParticipantPayments(
    this,
  );
  late final Teams teams = Teams(this);
  late final TeamMembers teamMembers = TeamMembers(this);
  late final Matches matches = Matches(this);
  late final MatchDependencies matchDependencies = MatchDependencies(this);
  late final CourtQueueEntries courtQueueEntries = CourtQueueEntries(this);
  late final DivisionPlacements divisionPlacements = DivisionPlacements(this);
  late final SyncOutboxOperations syncOutboxOperations = SyncOutboxOperations(
    this,
  );
  late final SyncPullCheckpoints syncPullCheckpoints = SyncPullCheckpoints(
    this,
  );
  late final SyncConflicts syncConflicts = SyncConflicts(this);
  late final Index playersDisplayNameIdx = Index(
    'players_display_name_idx',
    'CREATE INDEX players_display_name_idx ON players (display_name)',
  );
  late final Index eventsStatusScheduledAtIdx = Index(
    'events_status_scheduled_at_idx',
    'CREATE INDEX events_status_scheduled_at_idx ON events (status, scheduled_at)',
  );
  late final Index eventDivisionsEventIdIdx = Index(
    'event_divisions_event_id_idx',
    'CREATE INDEX event_divisions_event_id_idx ON event_divisions (event_id)',
  );
  late final Index eventDivisionsActiveNameIdx = Index(
    'event_divisions_active_name_idx',
    'CREATE UNIQUE INDEX event_divisions_active_name_idx ON event_divisions (event_id, lower(name)) WHERE deleted_at IS NULL',
  );
  late final Index eventParticipantsPlayerIdIdx = Index(
    'event_participants_player_id_idx',
    'CREATE INDEX event_participants_player_id_idx ON event_participants (player_id)',
  );
  late final Index eventParticipantsActivePlayerIdx = Index(
    'event_participants_active_player_idx',
    'CREATE UNIQUE INDEX event_participants_active_player_idx ON event_participants (event_id, player_id) WHERE deleted_at IS NULL',
  );
  late final Index divisionParticipantsEventParticipantIdx = Index(
    'division_participants_event_participant_idx',
    'CREATE INDEX division_participants_event_participant_idx ON division_participants (event_participant_id)',
  );
  late final Index divisionParticipantsActiveEntryIdx = Index(
    'division_participants_active_entry_idx',
    'CREATE UNIQUE INDEX division_participants_active_entry_idx ON division_participants (division_id, event_participant_id) WHERE deleted_at IS NULL',
  );
  late final Index participantPaymentsActiveEventScopeIdx = Index(
    'participant_payments_active_event_scope_idx',
    'CREATE UNIQUE INDEX participant_payments_active_event_scope_idx ON participant_payments (event_participant_id) WHERE division_id IS NULL AND deleted_at IS NULL',
  );
  late final Index participantPaymentsActiveDivisionScopeIdx = Index(
    'participant_payments_active_division_scope_idx',
    'CREATE UNIQUE INDEX participant_payments_active_division_scope_idx ON participant_payments (event_participant_id, division_id) WHERE division_id IS NOT NULL AND deleted_at IS NULL',
  );
  late final Index teamsDivisionIdIdx = Index(
    'teams_division_id_idx',
    'CREATE INDEX teams_division_id_idx ON teams (division_id)',
  );
  late final Index teamMembersPlayerIdIdx = Index(
    'team_members_player_id_idx',
    'CREATE INDEX team_members_player_id_idx ON team_members (player_id)',
  );
  late final Index matchesDivisionStatusIdx = Index(
    'matches_division_status_idx',
    'CREATE INDEX matches_division_status_idx ON matches (division_id, status, sequence_number)',
  );
  late final Index matchDependenciesDestinationIdx = Index(
    'match_dependencies_destination_idx',
    'CREATE INDEX match_dependencies_destination_idx ON match_dependencies (destination_match_id)',
  );
  late final Index matchDependenciesActiveDestinationSlotIdx = Index(
    'match_dependencies_active_destination_slot_idx',
    'CREATE UNIQUE INDEX match_dependencies_active_destination_slot_idx ON match_dependencies (destination_match_id, destination_slot) WHERE deleted_at IS NULL',
  );
  late final Index courtQueueEntriesActivePositionIdx = Index(
    'court_queue_entries_active_position_idx',
    'CREATE UNIQUE INDEX court_queue_entries_active_position_idx ON court_queue_entries (event_id, queue_position) WHERE deleted_at IS NULL',
  );
  late final Index courtQueueEntriesActiveMatchIdx = Index(
    'court_queue_entries_active_match_idx',
    'CREATE UNIQUE INDEX court_queue_entries_active_match_idx ON court_queue_entries (match_id) WHERE deleted_at IS NULL',
  );
  late final Index divisionPlacementsActivePositionIdx = Index(
    'division_placements_active_position_idx',
    'CREATE UNIQUE INDEX division_placements_active_position_idx ON division_placements (division_id, position) WHERE deleted_at IS NULL',
  );
  late final Index divisionPlacementsActiveTeamIdx = Index(
    'division_placements_active_team_idx',
    'CREATE UNIQUE INDEX division_placements_active_team_idx ON division_placements (division_id, team_id) WHERE deleted_at IS NULL',
  );
  late final Index syncOutboxEligibilityIdx = Index(
    'sync_outbox_eligibility_idx',
    'CREATE INDEX sync_outbox_eligibility_idx ON sync_outbox_operations (status, next_eligible_at, created_at, id)',
  );
  late final Index syncOutboxEntityIdx = Index(
    'sync_outbox_entity_idx',
    'CREATE INDEX sync_outbox_entity_idx ON sync_outbox_operations (entity_type, entity_id)',
  );
  late final Index syncConflictsUnresolvedIdx = Index(
    'sync_conflicts_unresolved_idx',
    'CREATE INDEX sync_conflicts_unresolved_idx ON sync_conflicts (status, detected_at)',
  );
  late final Index syncConflictsEntityIdx = Index(
    'sync_conflicts_entity_idx',
    'CREATE INDEX sync_conflicts_entity_idx ON sync_conflicts (entity_type, entity_id)',
  );
  @override
  Iterable<TableInfo<Table, Object?>> get allTables =>
      allSchemaEntities.whereType<TableInfo<Table, Object?>>();
  @override
  List<DatabaseSchemaEntity> get allSchemaEntities => [
    players,
    events,
    eventDivisions,
    eventParticipants,
    divisionParticipants,
    participantPayments,
    teams,
    teamMembers,
    matches,
    matchDependencies,
    courtQueueEntries,
    divisionPlacements,
    syncOutboxOperations,
    syncPullCheckpoints,
    syncConflicts,
    playersDisplayNameIdx,
    eventsStatusScheduledAtIdx,
    eventDivisionsEventIdIdx,
    eventDivisionsActiveNameIdx,
    eventParticipantsPlayerIdIdx,
    eventParticipantsActivePlayerIdx,
    divisionParticipantsEventParticipantIdx,
    divisionParticipantsActiveEntryIdx,
    participantPaymentsActiveEventScopeIdx,
    participantPaymentsActiveDivisionScopeIdx,
    teamsDivisionIdIdx,
    teamMembersPlayerIdIdx,
    matchesDivisionStatusIdx,
    matchDependenciesDestinationIdx,
    matchDependenciesActiveDestinationSlotIdx,
    courtQueueEntriesActivePositionIdx,
    courtQueueEntriesActiveMatchIdx,
    divisionPlacementsActivePositionIdx,
    divisionPlacementsActiveTeamIdx,
    syncOutboxEligibilityIdx,
    syncOutboxEntityIdx,
    syncConflictsUnresolvedIdx,
    syncConflictsEntityIdx,
  ];
  @override
  int get schemaVersion => 2;
  @override
  DriftDatabaseOptions get options =>
      const DriftDatabaseOptions(storeDateTimeAsText: true);
}
