import 'domain_failure.dart';
import 'domain_validation.dart';

/// Deterministic metadata supplied by callers rather than generated by a clock.
final class RecordMetadata {
  RecordMetadata({
    required this.createdAt,
    required this.updatedAt,
    required this.recordVersion,
    this.deletedAt,
  }) {
    requireUtc(createdAt, field: 'createdAt');
    requireUtc(updatedAt, field: 'updatedAt');
    if (deletedAt case final deletedAt?) {
      requireUtc(deletedAt, field: 'deletedAt');
    }
    requireNonNegative(recordVersion, field: 'recordVersion');

    if (updatedAt.isBefore(createdAt)) {
      throw const ValidationFailure(
        field: 'updatedAt',
        message: 'updatedAt cannot be before createdAt.',
      );
    }
    if (deletedAt case final deletedAt?) {
      if (deletedAt.isBefore(updatedAt)) {
        throw const ValidationFailure(
          field: 'deletedAt',
          message: 'deletedAt cannot be before updatedAt.',
        );
      }
    }
  }

  final DateTime createdAt;
  final DateTime updatedAt;
  final int recordVersion;
  final DateTime? deletedAt;

  bool get isDeleted => deletedAt != null;
}
